spring.application.name=my-blog-api

## default port is 8080 by Tomcat
server.port=8000

### databse connection
spring.datasource.username=root
spring.datasource.password=M.ysql@123
spring.datasource.url=jdbc:mysql://localhost:3306/spring_blog_db


#spring.jpa.hibernate.ddl-auto=create
#server.error.include-message=always